[book]
authors = ["Technology Innovation Institute - SSRC"]
language = "en"
multilingual = false
src = "src"
title = "Ghaf - Documentation for TII SSRC Secure Technologies: Ghaf Framework"

[output.html]
default-theme = "navy"
