name: doc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: build doc and deploy to gh pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nix
        uses: ./
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run: cachix use cachix
      - uses: cachix/install-nix-actions@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.VILVO_GHA_ACCESS_TOKEN }}
      - name: build
        run: nix build .#doc
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.VILVO_GHA_ACCESS_TOKEN }}
          publish_dir: ./result
