name: doc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: build doc and deploy to gh pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-actions@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: build
        run: nix build .#doc
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.VILVO_GHA_ACCESS_TOKEN }}
          publish_dir: ./result
